let words = [
    { word: "reflection", hint: "Image produced by a mirror" },
    { word: "discussion", hint: "Exchange of ideas or opinions" },
    { word: "journey", hint: "Travel from one place to another" },
    { word: "adventure", hint: "Exciting or unusual experience" },
    { word: "discovery", hint: "Finding or learning something new" },
    { word: "laughter", hint: "Sound produced by amusement" },
    { word: "mystery", hint: "Something that is difficult to understand" },
    { word: "whisper", hint: "Speak very softly" },
    { word: "silence", hint: "Absence of sound or noise" },
    { word: "memories", hint: "Recollections of past events" },
    { word: "courage", hint: "Quality of being brave or fearless" },
    { word: "inspiration", hint: "Stimulus to do creative work" },
    { word: "sensation", hint: "Physical feeling or perception" },
    { word: "determination", hint: "Firmness of purpose" },
    { word: "excitement", hint: "State of being emotionally aroused" },
    { word: "celebration", hint: "Act of commemorating an event" },
    { word: "harmony", hint: "State of agreement or concord" },
    { word: "passion", hint: "Intense emotion or enthusiasm" },
    { word: "curiosity", hint: "Desire to know or learn something" },
    { word: "imagination", hint: "Ability to create mental images" },
    { word: "nostalgia", hint: "Sentimental longing for the past" },
    { word: "dreams", hint: "Series of thoughts during sleep" },
    { word: "challenge", hint: "Task that tests one's abilities" },
    { word: "opportunity", hint: "Favorable chance for advancement" },
    { word: "kindness", hint: "Quality of being friendly and generous" },
    { word: "balance", hint: "State of equilibrium" },
    { word: "wonder", hint: "Feeling of admiration or amazement" },
    { word: "connection", hint: "Link or association" },
    { word: "simplicity", hint: "Quality of being uncomplicated" },
    { word: "gratitude", hint: "Feeling of appreciation or thanks" },
    { word: "freedom", hint: "State of being unrestricted" },
    { word: "wisdom", hint: "Knowledge and experience" },
    { word: "tranquility", hint: "State of calmness or peace" },
    { word: "compassion", hint: "Feeling of sympathy or pity" },
    { word: "optimism", hint: "Hopefulness about the future" },
    { word: "strength", hint: "Quality of being physically or mentally strong" },
    { word: "beauty", hint: "Quality that pleases the senses" },
    { word: "forgiveness", hint: "Act of pardoning someone" },
    { word: "confidence", hint: "Belief in oneself or one's abilities" },
    { word: "patience", hint: "Ability to endure waiting or delay" },
    { word: "integrity", hint: "Quality of being honest and moral" },
    { word: "purpose", hint: "Reason for which something is done" },
    { word: "success", hint: "Achievement of one's goals" },
    { word: "perseverance", hint: "Persistence in spite of difficulties" },
    { word: "laughter", hint: "Sound produced by amusement" },
    { word: "happiness", hint: "State of being happy or content" },
    { word: "joy", hint: "Feeling of great pleasure or happiness" },
    { word: "friendship", hint: "Relationship between friends" },
    { word: "love", hint: "Strong affection or fondness" },
    { word: "compassion", hint: "Feeling of sympathy or pity" },
    { word: "faith", hint: "Belief in something without proof" },
    { word: "hope", hint: "Feeling of expectation and desire" },
    { word: "courage", hint: "Quality of being brave or fearless" },
    { word: "kindness", hint: "Quality of being friendly and generous" },
    { word: "compassion", hint: "Feeling of sympathy or pity" },
    { word: "grace", hint: "Elegance or beauty of movement" },
    { word: "forgiveness", hint: "Act of pardoning someone" },
    { word: "generosity", hint: "Quality of being generous" },
    { word: "gratitude", hint: "Feeling of appreciation or thanks" },
    { word: "faith", hint: "Belief in something without proof" },
    { word: "simplicity", hint: "Quality of being uncomplicated" },
    { word: "compassion", hint: "Feeling of sympathy or pity" },
    { word: "patience", hint: "Ability to endure waiting or delay" },
    { word: "wisdom", hint: "Knowledge and experience" },
    { word: "serenity", hint: "State of being calm and peaceful" },
    { word: "inspiration", hint: "Stimulus to do creative work" },
    { word: "joy", hint: "Feeling of great pleasure or happiness" },
    { word: "happiness", hint: "State of being happy or content" },
    { word: "freedom", hint: "State of being unrestricted" },
    { word: "optimism", hint: "Hopefulness about the future" },
    { word: "success", hint: "Achievement of one's goals" },
    { word: "kindness", hint: "Quality of being friendly and generous" },
    { word: "compassion", hint: "Feeling of sympathy or pity" },
    { word: "grace", hint: "Elegance or beauty of movement" },
    { word: "forgiveness", hint: "Act of pardoning someone" },
    { word: "generosity", hint: "Quality of being generous" },
    { word: "gratitude", hint: "Feeling of appreciation or thanks" },
    { word: "faith", hint: "Belief in something without proof" },
    { word: "simplicity", hint: "Quality of being uncomplicated" },
    { word: "compassion", hint: "Feeling of sympathy or pity" },
    { word: "patience", hint: "Ability to endure waiting or delay" },
    { word: "wisdom", hint: "Knowledge and experience" },
    { word: "serenity", hint: "State of being calm and peaceful" },
    { word: "inspiration", hint: "Stimulus to do creative work" },
    { word: "dreams", hint: "Series of thoughts during sleep" },
    { word: "challenge", hint: "Task that tests one's abilities" },
    { word: "opportunity", hint: "Favorable chance for advancement" },
    { word: "kindness", hint: "Quality of being friendly and generous" },
    { word: "balance", hint: "State of equilibrium" },
    { word: "wonder", hint: "Feeling of admiration or amazement" },
    { word: "connection", hint: "Link or association" },
    { word: "simplicity", hint: "Quality of being uncomplicated" },
    { word: "gratitude", hint: "Feeling of appreciation or thanks" },
    { word: "freedom", hint: "State of being unrestricted" },
    { word: "wisdom", hint: "Knowledge and experience" },
    { word: "tranquility", hint: "State of calmness or peace" },
    { word: "compassion", hint: "Feeling of sympathy or pity" },
    { word: "optimism", hint: "Hopefulness about the future" },
    { word: "strength", hint: "Quality of being physically or mentally strong" },
    { word: "beauty", hint: "Quality that pleases the senses" },
    { word: "forgiveness", hint: "Act of pardoning someone" },
    { word: "confidence", hint: "Belief in oneself or one's abilities" },
    { word: "patience", hint: "Ability to endure waiting or delay" },
    { word: "integrity", hint: "Quality of being honest and moral" },
    { word: "purpose", hint: "Reason for which something is done" },
    { word: "success", hint: "Achievement of one's goals" },
    { word: "perseverance", hint: "Persistence in spite of difficulties" },
    { word: "laughter", hint: "Sound produced by amusement" },
    { word: "happiness", hint: "State of being happy or content" },
    { word: "joy", hint: "Feeling of great pleasure or happiness" },
    { word: "friendship", hint: "Relationship between friends" },
    { word: "love", hint: "Strong affection or fondness" },
    { word: "compassion", hint: "Feeling of sympathy or pity" },
    { word: "faith", hint: "Belief in something without proof" },
    { word: "hope", hint: "Feeling of expectation and desire" },
    { word: "courage", hint: "Quality of being brave or fearless" },
    { word: "kindness", hint: "Quality of being friendly and generous" },
    { word: "compassion", hint: "Feeling of sympathy or pity" },
    { word: "grace", hint: "Elegance or beauty of movement" },
    { word: "forgiveness", hint: "Act of pardoning someone" },
    { word: "generosity", hint: "Quality of being generous" },
    { word: "gratitude", hint: "Feeling of appreciation or thanks" },
    { word: "faith", hint: "Belief in something without proof" },
    { word: "simplicity", hint: "Quality of being uncomplicated" },
    { word: "compassion", hint: "Feeling of sympathy or pity" },
    { word: "patience", hint: "Ability to endure waiting or delay" },
    { word: "wisdom", hint: "Knowledge and experience" },
    { word: "serenity", hint: "State of being calm and peaceful" },
    { word: "inspiration", hint: "Stimulus to do creative work" },
    { word: "joy", hint: "Feeling of great pleasure or happiness" },
    { word: "happiness", hint: "State of being happy or content" },
    { word: "freedom", hint: "State of being unrestricted" },
    { word: "optimism", hint: "Hopefulness about the future" },
    { word: "success", hint: "Achievement of one's goals" },
    { word: "kindness", hint: "Quality of being friendly and generous" },
    { word: "compassion", hint: "Feeling of sympathy or pity" },
    { word: "grace", hint: "Elegance or beauty of movement" },
    { word: "forgiveness", hint: "Act of pardoning someone" },
    { word: "generosity", hint: "Quality of being generous" },
    { word: "gratitude", hint: "Feeling of appreciation or thanks" },
    { word: "faith", hint: "Belief in something without proof" },
    { word: "simplicity", hint: "Quality of being uncomplicated" },
    { word: "compassion", hint: "Feeling of sympathy or pity" },
    { word: "patience", hint: "Ability to endure waiting or delay" },
    { word: "wisdom", hint: "Knowledge and experience" },
    { word: "serenity", hint: "State of being calm and peaceful" },
    { word: "inspiration", hint: "Stimulus to do creative work" }
];
